### ISSUE TITLE
[SVE] TC-DGGEN-2.1 inconsistency with test plan

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#12]
From chip-test-scripts created by [ericzijian1994](https://github.com/ericzijian1994): CHIP-Specifications/chip-test-scripts#667  

## Description:
In TC-DGGEN-2.1, the scripts and test plan with eventTrigger are inconsistent. And the DUT no longer requires step 9c to trigger an unknown function.

```yaml
    - label:
          "Step 9c: When configured TRUE, Node has been configured with one or
          more test event triggers by virtue of the internally programmed non
          zero EnableKey value"
      runIf: IsExpectedValue
      PICS: DGGEN.S.C00.Rsp
      command: "TestEventTrigger"
      arguments:
          values:
              - name: "EnableKey"
                value: TEST_EVENT_ENABLE_KEY
              - name: "EventTrigger"
                value: TEST_EVENT_TRIGGER_KEY
```

In addition, the script has some descriptive errors at line 479: `Step 10c` should be `Step 10d`

## Steps to reproduce:
`./chip-tool generaldiagnostics test-event-trigger hex:00112233445566778899aabbccddeeff 0x0000000000000003 1 0`

## Additional Info:
Test plan: [general_diagnostics.adoc](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc)
