### ISSUE TITLE
[TC-Mode Base- 1.1] Yaml Script has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#133]
### Description:

- [ ] **TC-LWM-1.1**

- Step 3 - In Test plan there is no features in feature map list, But Script is verifying the "LWM.S.F00(DEPONOFF)" feature.

- Step 4c - In Test Plan there is no Feature dependent attribute(DEPONOFF)  in AttributeList, But Script is verifying OnMode(0x0003) attribute.

- [ ] **TC-TCCM-1.1**

- Step 3 - In Test plan there is no features in feature map list, But Script is verifying the "TCCM.S.F00(DEPONOFF)" feature.

- Step 4c - In Test Plan there is no Feature dependent attribute(DEPONOFF)  in AttributeList, But Script is verifying OnMode(0x0003) attribute.

### Steps to reproduce:
TC-LWM-Steps 3, 4c
TC-TCCM-Steps 3, 4c

### Test Plan References:
   - https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_laundry_washer.adoc
   - https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_Refrigerator.adoc

### Yaml References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LWM_1_1.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_TCCM_1_1.yaml

**Comment by Survensa** [comment]
@raul-marquez-csa Here is how the yaml should be for this issue similar for both TC-LWM-1.1 & TC-TCCM-1.1

Actual Step 3 :

```
    - label: "Step 3: TH reads from the DUT the FeatureMap attribute."
      command: "readAttribute"
      attribute: "FeatureMap"
      PICS: "!TCCM.S.F00"
      response:
          value: 0
          constraints:
              type: bitmap32

    - label:
          "Step 3: TH reads from the DUT the FeatureMap attribute, bit 0: SHALL
          be 1 if and only if TCCM.S.F00(DEPONOFF)"
      command: "readAttribute"
      attribute: "FeatureMap"
      PICS: TCCM.S.F00
      response:
          constraints:
              type: bitmap32
              hasMasksSet: [0x1]
```
Expected Step 3 : 

```
    - label: "Step 3: TH reads from the DUT the FeatureMap attribute."
      command: "readAttribute"
      attribute: "FeatureMap"
      response:
          value: 0
          constraints:
              type: bitmap32
```

For STEP 4C below lines has to be removed :

```
    - label:
          "Step 4c: TH reads from the DUT the AttributeList attribute. 0x0003
          SHALL be included if and only if TCCM.S.F00(DEPONOFF)"
      PICS: TCCM.S.F00
      command: "readAttribute"
      attribute: "AttributeList"
      response:
          constraints:
              type: list
              contains: [3]
```
