### ISSUE TITLE
[Bug] CNET_4.9&4.10&4.11 start chip-tool test due to verification in 

### ISSUE THREAD

**Issue by DejinChen** [project-chip/matter-test-scripts#345]
### Describe the bug

In TC-CNET-4.9 & 4.10 & 4.11 tests, "start chip-tool test" step failed.

### Steps to reproduce the behavior

test TC-CNET-4.9 & 4.10 & 4.11 in TH v2.11-beta2+fall2024.

### Expected behavior

"start chip-tool test" step failed and skipped the remaining steps.

### PICS file

CNET.C=0
CNET.S.A0000=1
CNET.S.A0001=1
CNET.S.A0002=1
CNET.S.A0003=1
CNET.S.A0004=1
CNET.S.A0005=1
CNET.S.A0006=1
CNET.S.A0007=1
CNET.S.A0008=0
CNET.S.A0009=1
CNET.S.A000a=1
CNET.S.C01.Tx=1
CNET.S.C05.Tx=1
CNET.S.C07.Tx=1
CNET.S.C00.Rsp=1
CNET.S.C02.Rsp=0
CNET.S.C03.Rsp=1
CNET.S.C04.Rsp=1
CNET.S.C06.Rsp=1
CNET.S.C08.Rsp=1
CNET.S.F00=0
CNET.S.F01=1
CNET.S.F02=0
CNET.C.C00.Tx=0
CNET.C.C02.Tx=0
CNET.C.C03.Tx=0
CNET.C.C04.Tx=0
CNET.C.C06.Tx=0
CNET.C.C08.Tx=0
CNET.C.F00=0
CNET.C.F01=0
CNET.C.F02=0

### Screenshots

![image](https://github.com/user-attachments/assets/27a46ac5-cfa3-4f53-9216-a028053f0e1f)

### Environment

- TH version: [v2.11-beta2+fall2024]
- OS: Ubuntu 24 on RaspberryPi
- Browser: chrome

**Comment by raul-marquez-csa** [comment]
Hi @DejinChen,

- Can you provide the output from this script? `./scripts/th/th-doctor.sh`
- Can you provide the logs for the error you encountered?
- Against what app were you running the test?
- How/where do I input the PICS values from the description?

Thanks.

**Comment by DejinChen** [comment]
1 & 2
[th-doctor.sh.txt](https://github.com/user-attachments/files/16836891/th-doctor.sh.txt)
[UI_Test_Run_2024_09_02_19_14_50.log](https://github.com/user-attachments/files/16836894/UI_Test_Run_2024_09_02_19_14_50.log)
3. on TH version: [v2.11-beta2+fall2024], OS: Ubuntu 24 on RaspberryPi, Browser: chrome
4. I'm not sure what you mean. I just uploaded he PICS in `edit` of project in TH. PICS file:
[Network Commissioning Cluster Test Plan.xml.txt](https://github.com/user-attachments/files/16836974/Network.Commissioning.Cluster.Test.Plan.xml.txt)

**Comment by raul-marquez-csa** [comment]
Found a duplicate bug
[[Bug] TC-CNET-4.9 Test Failure #326](https://github.com/project-chip/matter-test-scripts/issues/326)

**Comment by KishokG** [comment]
QA facing the same issue in RPI device: https://github.com/project-chip/certification-tool/issues/192

**Comment by HirokiOgawa1129** [comment]
I am also facing this problem. I'm using v2.11+fall2024.
Which version of TH will fix this?

Do you edit the yaml file manually?
 I ran TC-CNET-4.10, how do I fix it?

**Comment by mlsg** [comment]
Hi, I am also facing the same issue with TC-CNET-4.10

Screenshot: 

![Image](https://github.com/user-attachments/assets/2c36110a-561f-47f5-b7d2-ba40296d1f1b)

**Comment by mlsg** [comment]
any updates on this issue? Can I fix the script somehow?

**Comment by rquidute** [comment]
Please check the usage of `verification` inside YAML scripts, it seems it can only be used along steps with  `command: "UserPrompt"` or  `disabled: true`.

**Comment by bilalahmaddev** [comment]
@rquidute what to change here:

    ```
- label:
          "Step 3: TH finds the index of the Networks list entry with NetworkID
          field value PIXIT.CNET.THREAD_1ST_OPERATIONALDATASET and saves it as
          'Userth_netidx'"
      verification: |
          TH finds the index of the Networks list entry with NetworkID
          field value PIXIT.CNET.THREAD_1ST_OPERATIONALDATASET and saves it as
          'Userth_netidx'
      cluster: "LogCommands"
      command: "UserPrompt"
      PICS: PICS_USER_PROMPT
      arguments:
          values:
              - name: "message"
                value: "Please enter 'y' for success"
              - name: "expectedValue"
                value: "y"

    - label:
```
