### ISSUE TITLE
[TC-OO-2.3] - Test Case failing due to OffWaitTime attribute value mismatch and throwing unexpected error during execution

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#6]
From chip-test-scripts created by [Ashwinigrl](https://github.com/Ashwinigrl): CHIP-Specifications/chip-test-scripts#638  

### Description:
[TC-OO-2.3] - Steps 12b and 21b failing due to OffWaitTime attribute value mismatch and throwing unexpected error during middle of the execution.

### Steps to reproduce:
Step 12b, 21b

### Snapt Shot: 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/98016634/acf98e3f-a8e2-493c-bfd9-aebaa2ad8600)

![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/98016634/fe72ee5b-f14b-4d93-8dba-c0e14d81f879)

### Logs:
[TC-OO-2.3.log](https://github.com/CHIP-Specifications/chip-test-scripts/files/12545477/TC-OO-2.3.log)

### Environment :
**TH Version:** TH Fall2023
**Sha:** 22538eb7

### Additional Info:

- DUT : All-clusters-app
- Endpoint : 1
- PICS used : [On-Off Cluster Test Plan.zip](https://github.com/CHIP-Specifications/chip-test-scripts/files/12545454/On-Off.Cluster.Test.Plan.zip)

**Comment by raju-apple** [comment]
@Ashwinigrl is this still an issue in the latest TH release ?

**Comment by raju-apple** [comment]
@raju-apple TC-OO-2.3 Test case is verified with latest TH image(Version: TH Fall2023 Sha: 3f84bff5) still facing the same issue. 

**PICS file used:**
[On-Off Cluster Test Plan .txt](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039305/On-Off.Cluster.Test.Plan.txt)

**Reference log:**
[Tc-OO-2.3.pdf](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039308/Tc-OO-2.3.pdf)
[TC-OO-2.3.log](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039310/TC-OO-2.3.log)

**Endpoint used:** 1

**Comment by LookAtThisTree** [comment]
I am getting the same error, the value of OffWaitTime is usually 151 in my case. Let's focus on steps from 11a to 12b:

- 11a:Sends OffWithEffect command to DUT
At this point the DUT should enter Delayed Off state and OffWaitTime should start countdown from 300 ds to 0 ds.

- 11b:Reads OnOff attribute from DUT
First attribute read.

- 11b:Reads OnTime attribute from DUT
Second attribute read.

- 11b:Reads OffWaitTime attribute from DUT
Third attribute read.

- Wait 10000ms
Wait 10 seconds.

- 12a:Sends OnWithTimedOff command to DUT
This command should not affect a countdown.

- 12b:Reads OnOff attribute from DUT
Fourth attribute read.

- 12b:Reads OnTime attribute from DUT
Fifth attribute read.

- 12b:Reads OffWaitTime attribute from DUT
Finally read of the OffWaitTime that is assumed to happen exactly after 10 seconds from OffWithEffect command being called.

So, there are 5 attribute reads and 1 command (so 6 commands in total) executed between start of the OffWaitTime countdown and read of the OffWaitTime attribute. I suspected that each attribute read and command adds some delay, so I started commenting out the intermediate steps, one by one:

| Number of commands commented out between steps 11a and 12b | OffWaitTime value | Test result |
| --- | --- | --- |
| 0 | 151 | FAILED |
| 1 | 158 | FAILED |
| 2 | 164 | FAILED |
| 3 | 172 | PASSED |
| 4 | 180 | PASSED |
| 5 | 186 | PASSED |
| 6 | 193 | PASSED |

It clearly shows that execution of each command/attribute read takes about 5 - 10 ds. I do believe that those delay is mostly caused by TH processing rather than DUT/network. I am getting similar results both using `chip-lighting-app` running on TH as well as my real DUT. I had no issues with this test on TH 2.6.

Apart from this issue I also think that the 15% tolerance is improperly applied to many steps in this test. For example steps from 10d to 10e:

- 10d:Sends OnWithTimedOff command to DUT
```
    - label: "10d:Sends OnWithTimedOff command to DUT"
      command: "OnWithTimedOff"
      PICS: OO.S.C42.Rsp
      arguments:
          values:
              - name: "OnOffControl"
                value: 1
              - name: "OnTime"
                value: 300
              - name: "OffWaitTime"
                value: 300
```

- 10e:Reads OnTime attribute from DUT
```
    - label: "10e:Reads OnTime attribute from DUT"
      command: "readAttribute"
      attribute: "OnTime"
      PICS: OO.S.A4001 && OO.S.C42.Rsp
      response:
          constraints:
              minValue: 255
              maxValue: 345
```
Why the maxValue is 345? Of course this is 300 + 15% * 300, but any value above 300 indicates a bug. The OnTime attribute can only decrement as time goes by and it was set to 300 in step 10e.

Also the absolute value of the tolerance shrinks after as the time goes by, that seems counterlogical. For example the tolerance of OffWaitTime at step 11b, so when the countdown starts, is 45 ds, in step 12b, so after 10 seconds and a few commands executed, the tolerance is 30 ds. Why?

BTW, the `PIXIT.OO.MaxCommunicationTurnaround` from On/Off PICS seems not to work.
